### ISSUE TITLE
Unknown property exception "serialNumberHex" thrown when trying to authenticate user.

### ISSUE THREAD

**Issue by reviskar** [SK-EID/smart-id-php-client#1]
Hi! Tring to use this library results in an "Undefined property (serialNumberHex)" exception.

### Preconditions
"sk-id-solutions/smart-id-php-client": "~1.0"
php: 7.0.17

### Steps to reproduce
1. Use test environment (https://sid.demo.sk.ee/smart-id-rp/v1/)
2. call `SmartIdAuthenticationResponse::authenticate()` having the parameters correctly set
3. get the "Undefined property (serialNumberHex)" exception thrown.

When `SmartIdAuthenticationResponse::getCertificateInstance()` is called after `AuthenticationRequestBuilder::authenticate()` then a `new AuthenticationCertificate()` is called and `PropertyMapper:fromArray() ` tries to map `serialNumberHex` as a class propery whitch does not exist. I personally see two solutions to this: 
1. Ignore attributes that does not exist in the class with a simple `is_property()` check
2. Add the missing `serialNumberHex` property to the `AuthenticationCertificate` class

Thanks in advance.

**Comment by jeserkin** [comment]
As it turns out newer PHP version can read more properties in, than previous one and therefore it came up.
Ignoring missing properties feels like a bad option.
