### ISSUE TITLE
Fatal error: Uncaught Sk\SmartId\Exception\UserAccountNotFoundException

### ISSUE THREAD

**Issue by kriit24** [SK-EID/smart-id-php-client#12]
Lisage example "Example of configuring the client"
rida use Sk\SmartId\Exception\SmartIdException;

**Comment by kriit24** [comment]
Lisaks SmartId/Sk/SmartId/Api/SmartIdRestConnector.php
failis muutke 
throw new UserAccountNotFoundException();
koodiks
throw new UserAccountNotFoundException($e->getMessage());

**Comment by jalukse** [comment]
Done. 
Version 1.5
053fe5f3b4bd715be305481e764d95aeddbe9d93
