### ISSUE TITLE
SID Demo SSL key pinning changes have not reached to `packagist.org`

### ISSUE THREAD

**Issue by vellotis** [SK-EID/smart-id-php-client#24]
A new release to packagist.org would be great. The SID Demo SSL key pinning changes after v1.5.1 release have not reached there. Saves the other potential integrators a lot of time. Took me few hours to find out that the `packagist` and `github` latest do not match.

**Comment by jalukse** [comment]
New version is available at https://packagist.org/packages/sk-id-solutions/smart-id-php-client
