### ISSUE TITLE
SessionStatus - interactionFlowUsed is not set.

### ISSUE THREAD

**Issue by userrainlaansalu** [SK-EID/smart-id-php-client#35]
Hi!

I updated to version 2.2 and after some modifications I got stuck with following error:

Uncaught TypeError: Return value of Sk\SmartId\Api\Data\SessionStatus::getInteractionFlowUsed() must be of the type string, null returned in ../sk-id-solutions/smart-id-php-client/src/Sk/SmartId/Api/Data/SessionStatus.php:154

My authenticate code is as follows:
```
$authenticationResponse = $client->authentication()
  ->createAuthentication()
  ->withSemanticsIdentifier( $identity )
  ->withAuthenticationHash( $authenticationHash )
  ->withAllowedInteractionsOrder([Interaction::ofTypeDisplayTextAndPIN("Text and pin")])
  ->withCertificateLevel( CertificateLevelCode::QUALIFIED )
  ->authenticate();
```

If I add 
`private $interactionFlowUsed = "displayTextAndPin";`
as default to SessionStatus class, it works.

**Comment by aasaru** [comment]
Demo environment doesn't return the interaction flow used this is probably why you get null.
It shouldn't happen in production but just in case I will update the method to allow returning a null value.
