### ISSUE TITLE
Error! Response is not valid! Error(s): Signature verification failed.

### ISSUE THREAD

**Issue by fixedlv** [SK-EID/smart-id-php-client#41]
Hello there.

So basically I use 2 calls to identify a customer

1st I call session id with startAuthenticationAndReturnSessionId and semanticsIdentifier
Then continuously i check for session  with createSessionStatusFetcher but when i get response and i try to validate it with authenticationResponseValidator i get runtime exception

An uncaught Exception was encountered
Type: RuntimeException
Message: Error! Response is not valid! Error(s): Signature verification failed.

And $authenticationResponse->getDocumentNumber() is empty

Path to trusted certificates is defined and when i use authenticate method everything is working correctly

For me it seems strange when i try to validate the session no the user i get issue with this

Thanks

**Comment by fixedlv** [comment]
Sorry - close this

I had a typo and authentication hash had a dot at the end of it

**Comment by jalukse** [comment]
Good that you found solution for your issue.
